language: java
sudo: required

services:
  - docker

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
  - docker build -t $DOCKER_USERNAME/osgi.example.kubernetes starter
  - docker push $DOCKER_USERNAME/osgi.example.kubernetes
 
