language: java
sudo: required

services:
  - docker
  
before-deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t $DOCKER_USERNAME/osgi.example.kubernetes .
  - docker push $DOCKER_USERNAME/osgi.example.kubernetes
 
