language: java
sudo: required

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t $DOCKER_USERNAME/osgi.example.kubernetes starter
  - docker push $DOCKER_USERNAME/osgi.example.kubernetes
 
