language: java
sudo: required

services:
  - docker

before_install:
  - docker build -t "$DOCKER_USERNAME"/osgi.example.kubernetes starter
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/osgi.example.kubernetes
 
